export const CREATE_ADDRESS = 'CREATE_ADDRESS';
export const CREATE_ADDRESS_FAILURE = 'CREATE_ADDRESS_FAILURE';
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS';

export const CUSTOMER_DETAILS_KEY = 'CUSTOMER_DETAILS_KEY';
