export const CART_ID_KEY = 'CART_ID_KEY';

export const FETCH_CART_ID = 'FETCH_CART_ID';
export const FETCH_CART_ID_SUCCESS = 'FETCH_CART_ID_SUCCESS';

export const ADD_CART = 'ADD_CART';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_FAILURE = 'ADD_CART_FAILURE';

export const FETCH_CART_PRODUCTS = 'FETCH_CART_PRODUCTS';
export const FETCH_CART_PRODUCTS_SUCCESS = 'FETCH_CART_PRODUCTS_SUCCESS';
export const FETCH_CART_PRODUCTS_FAILURE = 'FETCH_CART_PRODUCTS_FAILURE';

export const EMPTY_CART = 'EMPTY_CART';
export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS';
export const EMPTY_CART_FAILURE = 'EMPTY_CART_FAILURE';

export const REMOVE_CART_PRODUCT = 'REMOVE_CART_PRODUCT';
export const REMOVE_CART_PRODUCT_SUCCESS = 'REMOVE_CART_PRODUCT_SUCCESS';
export const REMOVE_CART_PRODUCT_FAILURE = 'REMOVE_CART_PRODUCT_FAILURE';

export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_CART_FAILURE = 'UPDATE_CART_FAILURE';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';

export const CART_COUNT_KEY = 'CART_COUNT_KEY';
